name: Publish Package

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - run: npm install -g npm@latest

      - run: npm ci

      - run: echo "registry=https://registry.npmjs.org/" >> ~/.npmrc

      - run: npm publish
        env:
          NPM_CONFIG_PROVENANCE: true
